# Generated by Django 5.2.10 on 2026-01-19 05:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10,
                 validators=[django.core.validators.MinValueValidator(0.01)])),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='products', to='store.store')),
            ],
        ),
    ]
