# Generated by Django 5.2.10 on 2026-01-19 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(
                    max_length=254,
                    unique=True,
                    validators=[django.core.validators.EmailValidator()],
                )),
                ('password', models.CharField(
                    max_length=128,
                    validators=[
                        django.core.validators.RegexValidator(
                            message=(
                                'Password must contain at least one '
                                'uppercase letter and one digit.'
                            ),
                            regex='^(?=.*[A-Z])(?=.*\\d).+$',
                        )
                    ],
                )),
                ('user_type', models.CharField(
                    choices=[('buyer', 'Buyer'), ('vendor', 'Vendor')],
                    max_length=50,
                )),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
