# Generated by Django 5.2.10 on 2026-01-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('store_category', models.CharField(
                    choices=[
                        ('electronics', 'Electronics'),
                        ('fashion', 'Fashion'),
                        ('groceries', 'Groceries'),
                        ('home_appliances', 'Home Appliances'),
                        ('books', 'Books'),
                        ('toys', 'Toys'),
                    ],
                    max_length=50,
                )),
            ],
        ),
    ]
