# Generated by Django 5.2.10 on 2026-01-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(
                default=False, help_text='True if the user purchased this product'),
        ),
    ]
